name: pysap
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip>=19.1.1
  - astropy>=3.2.1
  - jupyter>=1.0.0
  - matplotlib>=3.1.1
  - numpy>=1.16.4
  - pyqtgraph>=0.10.0
  - pip:
      - setuptools>=60.0.0
      - python-pysap>=0.1.0
      - modopt>=1.7.1
      - pysap-mri>=0.5.0
  
