name: CI

on:
  pull_request:
    branches:
     - develop
     - master
     - main

jobs:
  test-full:
    name: Full Test Suite
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: pysap

      - name: Check Conda
        run: |
          conda info
          conda list
          python --version

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew tap sfarrens/sf
          brew install bigmac libomp

      - name: Install Package Dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install -r develop.txt
          python -m pip install twine

      - name: Install PySAP
        run: |
          python -m pip install .
          python -c "import pysap; print(pysap.info())"

      - name: Run Tests
        run: |
          python -m pytest

      - name: Save Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: pytest.xml

      - name: Run Examples
        continue-on-error: true
        run: |
          python pysap/test/test_examples.py

      - name: Check Distribution
        run: |
          python setup.py sdist
          twine check dist/*

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests

  test-basic:
    name: Basic Test Suite
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9"]

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: pysap

      - name: Check Conda
        run: |
          conda info
          conda list
          python --version

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew tap sfarrens/sf
          brew install bigmac libomp

      - name: Install Package Dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install -r develop.txt

      - name: Install PySAP
        run: |
          python -m pip install .
          python -c "import pysap; print(pysap.info())"

      - name: Run Tests
        run: |
          python -m pytest
